//FIRST MAIN PROPERTY THAT CONTAINS ALL THE HTML ELEMENTS FOR REFERENCE
module.exports = {
    cardContainer : document.getElementById('card-container'),
    closeNewMovie : document.getElementById('close-new-movie'),
    genreButton : document.getElementById('genre-button'),
    genreErrorMessage : document.getElementById('error-message-genre'),
    genreForm : document.forms.editGenre,
    genreInput : document.forms.editGenre.genre,
    genreLabelCount : document.getElementsByClassName('genre-label-count'),
    genreLinkName : document.getElementsByClassName('genre-link-name'),
    genreSuccess : document.getElementById('genre-success'),
    listGenre : document.getElementsByClassName('list-genre'),
    listRating : document.getElementsByClassName('list-rating'),
    modalGenres : document.getElementById('modal-movie-genres'),
    modalOpener : document.getElementsByClassName('modal-opener'),
    modalPoster : document.getElementById('modal-movie-poster'),
    modalRating : document.getElementById('modal-movie-rating'),
    modalTitle : document.getElementById('modal-movie-title'),
    modalYear : document.getElementById('modal-movie-year'),
    movieCover : document.forms.movieCreator.cover,
    movieCreator : document.forms.movieCreator,
    movieGenreInput : document.forms.movieGenreInput,
    movieGenres : document.forms.movieCreator.genres,
    movieList: JSON.parse(localStorage.getItem("MovieDb")),
    movieModal : document.getElementById('movie-modal'),
    movieResult: document.getElementById('movie-result'),
    movieTitle : document.forms.movieCreator.title,
    movieYear : document.forms.movieCreator.year,
    movieYearInput : document.forms.movieYearInput,
    newMovieLink : document.getElementById('new-movie-link'),
    newMovieModal : document.getElementById('new-movie-modal'),
    ratingButton : document.getElementById('rating-button'),
    ratingCirle : document.getElementById('rating-circle'),
    ratingSort : document.getElementById('rating-sort'),
    selectedMovieQuestion : document.getElementById("selected-movie-question"),
    selectedRating : document.getElementById('selected-rating'),
    titleSort : document.getElementById('title-sort'),
    yearSort : document.getElementById('year-sort')
};
