//FIRST MAIN PROPERTY THAT CONTAINS ALL THE HTML ELEMENTS FOR REFERENCE
module.exports = {
    genreButton : document.getElementById('genre-button'),
    genreErrorMessage : document.getElementById('error-message-genre'),
    genreForm : document.forms.editGenre,
    genreInput : document.forms.editGenre.genre,
    genreSuccess : document.getElementById('genre-success'),
    listGenre : document.getElementsByClassName('list-genre'),
    listRating : document.getElementsByClassName('list-rating'),
    modalGenres : document.getElementById('modal-movie-genres'),
    modalOpener : document.getElementsByClassName('modal-opener'),
    modalPoster : document.getElementById('modal-movie-poster'),
    modalRating : document.getElementById('modal-movie-rating'),
    modalTitle : document.getElementById('modal-movie-title'),
    modalYear : document.getElementById('modal-movie-year'),
    movieCreator : document.getElementById('movie-creator'),
    movieGenreInput : document.forms.movieGenreInput,
    movieGenres : document.forms.movieAdder.genres,
    movieList: JSON.parse(localStorage.getItem("MovieDb")),
    movieModal : document.getElementById('movie-modal'),
    movieResult: document.getElementById('movie-result'),
    movieTable : document.getElementById('movie-table'),
    movieTitle : document.forms.movieAdder.title,
    movieYear : document.forms.movieAdder.year,
    movieYearInput : document.forms.movieYearInput,
    overlay : document.getElementById('overlay'),
    ratingButton : document.getElementById('rating-button'),
    ratingCirle : document.getElementById('rating-circle'),
    ratingSort : document.getElementById('rating-sort'),
    selectedMovieQuestion : document.getElementById("selected-movie-question"),
    selectedRating : document.getElementById('selected-rating'),
    titleSort : document.getElementById('title-sort'),
    yearSort : document.getElementById('year-sort')
};
